---
title: "Data Acquisition"
format: html
editor: visual
---

Sample code to get athlete results data:

We might need to refresh the `x-api-key` field from time to time

```{r}
library(tidyverse)
library(httr2)

# base request 
base_req <- 
  request("https://graphql-prod-4829.edge.aws.worldathletics.org/graphql") |>
  req_method("POST") |>
  req_headers(
    Accept = "*/*",
    `Sec-Fetch-Site` = "same-site",
    `Accept-Language` = "en-CA,en-US;q=0.9,en;q=0.8",
    `Sec-Fetch-Mode` = "cors",
    `Accept-Encoding` = "gzip, deflate", # i removed the `br` here, that was causing errors
    Origin = "https://worldathletics.org",
    `User-Agent` = "Mozilla/5.0",
    Referer = "https://worldathletics.org/",
   # `Content-Length` = "895",
    Connection = "keep-alive",
    `Sec-Fetch-Dest` = "empty",
    `x-amz-user-agent` = "aws-amplify/3.0.2",
    Priority = "u=3, i",
    `x-api-key` = "da2-tfydjxrdwnaydebwsodqefmibe" # might need to update this sometimes
  )

```

```{r}

get_results_data <- function(athlete_id, year) {
  base_req |>
  req_body_json(
    list(
      operationName = "GetSingleCompetitorResultsDate",
      variables = list(
        resultsByYear = year,
        resultsByYearOrderBy = "date",
        id = athlete_id
      ),query = "
      query GetSingleCompetitorResultsDate($id: Int, $resultsByYearOrderBy: String, $resultsByYear: Int) {
        getSingleCompetitorResultsDate(
          id: $id,
          resultsByYear: $resultsByYear,
          resultsByYearOrderBy: $resultsByYearOrderBy
        ) {
          parameters {
            resultsByYear
          }
          resultsByDate {
            date
            competition
            competitionId
            eventId
            venue
            indoor
            disciplineCode
            disciplineNameUrlSlug
            typeNameUrlSlug
            discipline
            country
            category
            race
            place
            mark
            wind
            notLegal
            resultScore
            remark
            competitionId
            eventId
          }
          __typename
        }
      }
    "
  ), 
  type = "application/json"
  ) |>
  req_perform() |>
  resp_body_json()
}
```

so for each distinct athlete in `olympics_data.csv` dataset

```{r}
# all athletes who have made an olympic games between 1996 and 2021. 
# We could probably add the 2024 olympics to this if we want, which would be a good idea.

athlete_links <- read_csv("https://raw.githubusercontent.com/awosoga/peaks-and-primes/refs/heads/master/olympics_data.csv") %>% 
  distinct(athlete_links) %>% 
  pull(athlete_links)

all_results <- tibble()
for (athlete_link in athlete_links) {
  Sys.sleep(0.5)
  athlete_id <- str_extract(athlete_link, "\\d+$")
  
  active_years <- 
  base_req %>% 
  req_body_json(list(
    operationName = "GetSingleCompetitorResultsDate",
    variables = list(id = athlete_id),
    query = "
      query GetSingleCompetitorResultsDate($id: Int) {
        getSingleCompetitorResultsDate(id: $id) {
          activeYears
        }
      }"
  )) %>% 
  req_perform() %>% 
  resp_body_json() %>% 
  pluck("data", "getSingleCompetitorResultsDate", "activeYears") %>% 
  list_c() %>% 
  parse_integer()
  
  results <- map(active_years, ~ get_results_data(athlete_id, .x))

  results_df <- 
    results %>% 
    bind_rows() %>% 
    unnest_wider(data) %>% 
    unnest_longer(resultsByDate) %>% 
    unnest_wider(resultsByDate) %>% 
    unnest_wider(parameters) %>% 
    janitor::clean_names() %>% 
    mutate(ahlete_id = athlete_id, 
           athlete_link = athlete_link)
  
  all_results <- bind_rows(all_results, results_df)
  
}

write_csv(all_results, "athlete_results_data.csv")

```

